### ISSUE TITLE
Issue with AWS DynamoDB Output 

### ISSUE THREAD

**Issue by yusuf-nathani** [Pentaho-SE-EMEA-APAC/pdi-aws#6]
Hi,

While connecting and inserting data with AWS DynamoDB Output, i am getting following error. Can you pl suggest what went wrong here ?

```
2018/04/12 16:59:02 - AWS DynamoDB Output.0 - ERROR (version 7.1.0.0-12, build 1 from 2017-05-16 17.18.02 by buildguy) : Unexpected error
2018/04/12 16:59:02 - AWS DynamoDB Output.0 - ERROR (version 7.1.0.0-12, build 1 from 2017-05-16 17.18.02 by buildguy) : java.lang.ClassCastException: [B cannot be cast to java.lang.Long
2018/04/12 16:59:02 - AWS DynamoDB Output.0 - 	at org.pentaho.kettle.steps.aws.dynamodb.DynamoDBOutput.processRow(DynamoDBOutput.java:203)
2018/04/12 16:59:02 - AWS DynamoDB Output.0 - 	at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
2018/04/12 16:59:02 - AWS DynamoDB Output.0 - 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by zyystudio** [comment]
Have you tried to add a select value step to cast it as a Long firstly before dynamodb output?

**Comment by adamfowleruk** [comment]
Can you please let me know the type (in PDI) of the item, and the exact value of the item in the row that is causing this issue?

This cast is surrounded by a type check - so it should be impossible for this to error, provided the data itself is truly a Java Long (which is a PDI Integer). This leads me to suspect you have badly formatted data saved in an Integer step in PDI. 

Please check your data and confirm its exact value.

**Comment by adamfowleruk** [comment]
I will close this issue within 7 days if I do not hear a reply.
