### ISSUE TITLE
NOt able to open the Dynamo DB Input/output

### ISSUE THREAD

**Issue by VJTableau** [Pentaho-SE-EMEA-APAC/pdi-aws#7]
Unable to open dialog for this step
java.lang.NoClassDefFoundError: org/pentaho/di/core/database/aws/dynamodb/DynamoDBDatabaseMeta
               at org.pentaho.kettle.steps.aws.dynamodb.DynamoDBOutputDialog.open(DynamoDBOutputDialog.java:179)
               at org.pentaho.di.ui.spoon.delegates.SpoonStepsDelegate.editStep(SpoonStepsDelegate.java:125)
               at org.pentaho.di.ui.spoon.Spoon.editStep(Spoon.java:8783)
               at org.pentaho.di.ui.spoon.trans.TransGraph.editStep(TransGraph.java:3072)
               at org.pentaho.di.ui.spoon.trans.TransGraph.mouseDoubleClick(TransGraph.java:755)
               at org.eclipse.swt.widgets.TypedListener.handleEvent(Unknown Source)
               at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
               at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
               at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
               at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
               at org.pentaho.di.ui.spoon.Spoon.readAndDispatch(Spoon.java:1347)
               at org.pentaho.di.ui.spoon.Spoon.waitForDispose(Spoon.java:7989)
               at org.pentaho.di.ui.spoon.Spoon.start(Spoon.java:9269)
               at org.pentaho.di.ui.spoon.Spoon.main(Spoon.java:662)
               at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
               at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
               at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
               at java.lang.reflect.Method.invoke(Unknown Source)
               at org.pentaho.commons.launcher.Launcher.main(Launcher.java:92)
Caused by: java.lang.ClassNotFoundException: org.pentaho.di.core.database.aws.dynamodb.DynamoDBDatabaseMeta
               at java.net.URLClassLoader.findClass(Unknown Source)
               at java.lang.ClassLoader.loadClass(Unknown Source)
               at java.lang.ClassLoader.loadClass(Unknown Source)
               at org.pentaho.di.core.plugins.KettleURLClassLoader.loadClassFromParent(KettleURLClassLoader.java:89)
               at org.pentaho.di.core.plugins.KettleURLClassLoader.loadClass(KettleURLClassLoader.java:108)
               at java.lang.ClassLoader.loadClass(Unknown Source)
               ... 19 more

**Comment by adamfowleruk** [comment]
Hello there! In order for me to be able to help you would you please answer the following for me?

1. What version of Pentaho Data Integration are you using? E.g. mentioned on the splash screen when you start it. Such as 8.0.0.0-28.

2. Have you unzipped the final pdi-aws folder so it resides in PENTAHO_HOME/client-tools/data-integration/plugins/ ?

3. Have you tried running spoondebug.bat under PENTAHO_HOME/client-tools/data-integration to start PDI, and looked at the detail in the spoondebug.txt file for other error messages?

4. Within PDI, if you go to the Tools menu and select Plugin Information, then choose 'Database' from the drop down. What does it say under 'libraries' for the plugin names 'AWS DynamoDB'?

Thanks in advance.
